name: web_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Regular.ttf
          style: normal
    - family: Felix Titling
      fonts:
        - asset: assets/fonts/felix-titling-mt.ttf
          style: normal
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          style: normal
    - family: Quattrocento
      fonts:
        - asset: assets/fonts/Quattrocento-Regular.ttf
          style: normal